
import { FoodItem, TranslationDictionary, Language } from './types';

export const MOCK_HISTORY: FoodItem[] = [
  {
    id: '1',
    image: 'https://picsum.photos/seed/granola/600/400',
    analysis: {
      productName: "Nature's Valley Granola",
      price: "$5.99",
      summary: "A decent source of fiber, but high in added sugars and contains some processed oils. Best consumed in moderation as part of a balanced diet.",
      ingredients: [
        { name: "Whole Grain Oats", rating: "GOOD", reason: "Excellent source of fiber and nutrients." },
        { name: "Sugar", rating: "POOR", reason: "High in empty calories and can contribute to weight gain." },
        { name: "Canola Oil", rating: "MODERATE", reason: "A processed oil, moderation is key." },
        { name: "Honey", rating: "MODERATE", reason: "A natural sugar, but still a sugar." },
        { name: "Salt", rating: "MODERATE", reason: "Essential for body functions, but excessive intake is harmful." },
        { name: "Soy Lecithin", rating: "NEUTRAL", reason: "An emulsifier, generally considered safe." }
      ]
    },
    location: "SuperMart, Downtown",
    scanDate: new Date(Date.now() - 86400000).toISOString(), // 1 day ago
  },
  {
    id: '2',
    image: 'https://picsum.photos/seed/yogurt/600/400',
    analysis: {
      productName: "Greek Yogurt",
      price: "$3.49",
      summary: "An excellent source of protein and probiotics. This plain version has no added sugar, making it a very healthy choice.",
      ingredients: [
        { name: "Cultured Pasteurized Grade A Nonfat Milk", rating: "GOOD", reason: "Provides protein and beneficial probiotics." },
        { name: "Live and Active Cultures", rating: "GOOD", reason: "Beneficial for gut health." }
      ]
    },
    location: "Health Food Store",
    scanDate: new Date(Date.now() - 2 * 86400000).toISOString(), // 2 days ago
  }
];

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', label: 'Italiano', flag: '🇮🇹' },
  { code: 'zh-CN', label: '简体中文', flag: '🇨🇳' },
  { code: 'zh-TW', label: '繁體中文', flag: '🇹🇼' },
  { code: 'ja', label: '日本語', flag: '🇯🇵' },
];

export const TRANSLATIONS: Record<Language, TranslationDictionary> = {
  en: {
    appTitle: "NutriScan AI",
    scanTab: "Scan Food",
    historyTab: "History",
    scanTitle: "Scan a New Food",
    scanSubtitle: "Upload a photo of a food product or enter details manually.",
    uploadClick: "Click to upload",
    uploadDrag: "or drag and drop an image",
    analyzing: "Analyzing...",
    analyzingDesc: "Our AI is examining the ingredients and nutritional information. This might take a moment.",
    historyTitle: "Your Food Diary",
    historyEmpty: "Your history is empty.",
    historyEmptyAction: "Go to the 'Scan Food' tab to analyze your first item!",
    detailSummary: "AI Health Summary",
    detailIngredients: "Ingredient Analysis",
    detailPrice: "Price",
    footer: "NutriScan AI. Making healthy choices easier.",
    analysisFailed: "Analysis Failed",
    unknownError: "An unknown error occurred.",
    textInputLabel: "Manually Enter Details",
    textInputPlaceholder: "Paste ingredients list, product name, or description here...",
    analyzeTextButton: "Analyze Text",
    orDivider: "OR",
    loginButton: "Sign in with Google",
    logoutButton: "Sign out",
    welcomeUser: "Hi, ",
  },
  es: {
    appTitle: "NutriScan AI",
    scanTab: "Escanear",
    historyTab: "Historial",
    scanTitle: "Escanear Nuevo Alimento",
    scanSubtitle: "Sube una foto de un producto o ingresa detalles manualmente.",
    uploadClick: "Clic para subir",
    uploadDrag: "o arrastra y suelta una imagen",
    analyzing: "Analizando...",
    analyzingDesc: "Nuestra IA está examinando los ingredientes y la información nutricional. Esto puede tardar un momento.",
    historyTitle: "Tu Diario de Alimentos",
    historyEmpty: "Tu historial está vacío.",
    historyEmptyAction: "¡Ve a la pestaña 'Escanear' para analizar tu primer artículo!",
    detailSummary: "Resumen de Salud IA",
    detailIngredients: "Análisis de Ingredientes",
    detailPrice: "Precio",
    footer: "NutriScan AI. Facilitando elecciones saludables.",
    analysisFailed: "Análisis Fallido",
    unknownError: "Ocurrió un error desconocido.",
    textInputLabel: "Ingresar Detalles Manualmente",
    textInputPlaceholder: "Pega la lista de ingredientes, nombre del producto o descripción aquí...",
    analyzeTextButton: "Analizar Texto",
    orDivider: "O",
    loginButton: "Iniciar sesión con Google",
    logoutButton: "Cerrar sesión",
    welcomeUser: "Hola, ",
  },
  fr: {
    appTitle: "NutriScan AI",
    scanTab: "Scanner",
    historyTab: "Historique",
    scanTitle: "Scanner un Aliment",
    scanSubtitle: "Téléchargez une photo ou entrez les détails manuellement.",
    uploadClick: "Cliquez pour télécharger",
    uploadDrag: "ou glissez-déposez une image",
    analyzing: "Analyse en cours...",
    analyzingDesc: "Notre IA examine les ingrédients et les informations nutritionnelles. Cela peut prendre un moment.",
    historyTitle: "Votre Journal Alimentaire",
    historyEmpty: "Votre historique est vide.",
    historyEmptyAction: "Allez dans l'onglet 'Scanner' pour analyser votre premier article !",
    detailSummary: "Résumé Santé IA",
    detailIngredients: "Analyse des Ingrédients",
    detailPrice: "Prix",
    footer: "NutriScan AI. Faciliter les choix sains.",
    analysisFailed: "Échec de l'analyse",
    unknownError: "Une erreur inconnue s'est produite.",
    textInputLabel: "Entrer les Détails Manuellement",
    textInputPlaceholder: "Collez la liste des ingrédients, le nom du produit ou la description ici...",
    analyzeTextButton: "Analyser le Texte",
    orDivider: "OU",
    loginButton: "Se connecter avec Google",
    logoutButton: "Se déconnecter",
    welcomeUser: "Salut, ",
  },
  de: {
    appTitle: "NutriScan AI",
    scanTab: "Scannen",
    historyTab: "Verlauf",
    scanTitle: "Neues Lebensmittel scannen",
    scanSubtitle: "Foto hochladen oder Details manuell eingeben.",
    uploadClick: "Zum Hochladen klicken",
    uploadDrag: "oder Bild hierher ziehen",
    analyzing: "Analysieren...",
    analyzingDesc: "Unsere KI prüft die Zutaten und Nährwertinformationen. Dies kann einen Moment dauern.",
    historyTitle: "Ihr Ernährungstagebuch",
    historyEmpty: "Ihr Verlauf ist leer.",
    historyEmptyAction: "Gehen Sie zum Tab 'Scannen', um Ihren ersten Artikel zu analysieren!",
    detailSummary: "KI-Gesundheitszusammenfassung",
    detailIngredients: "Zutatenanalyse",
    detailPrice: "Preis",
    footer: "NutriScan AI. Gesunde Entscheidungen leichter gemacht.",
    analysisFailed: "Analyse fehlgeschlagen",
    unknownError: "Ein unbekannter Fehler ist aufgetreten.",
    textInputLabel: "Details Manuell Eingeben",
    textInputPlaceholder: "Fügen Sie hier die Zutatenliste, den Produktnamen oder die Beschreibung ein...",
    analyzeTextButton: "Text Analysieren",
    orDivider: "ODER",
    loginButton: "Mit Google anmelden",
    logoutButton: "Abmelden",
    welcomeUser: "Hallo, ",
  },
  it: {
    appTitle: "NutriScan AI",
    scanTab: "Scansione",
    historyTab: "Cronologia",
    scanTitle: "Scansiona Nuovo Cibo",
    scanSubtitle: "Carica una foto o inserisci i dettagli manualmente.",
    uploadClick: "Clicca per caricare",
    uploadDrag: "o trascina e rilascia un'immagine",
    analyzing: "Analisi in corso...",
    analyzingDesc: "La nostra IA sta esaminando gli ingredienti e le informazioni nutrizionali. Potrebbe richiedere un momento.",
    historyTitle: "Il Tuo Diario Alimentare",
    historyEmpty: "La tua cronologia è vuota.",
    historyEmptyAction: "Vai alla scheda 'Scansione' per analizzare il tuo primo articolo!",
    detailSummary: "Riepilogo Salute IA",
    detailIngredients: "Analisi degli Ingredienti",
    detailPrice: "Prezzo",
    footer: "NutriScan AI. Scelte sane rese più facili.",
    analysisFailed: "Analisi Fallita",
    unknownError: "Si è verificato un errore sconosciuto.",
    textInputLabel: "Inserisci Manualmente i Dettagli",
    textInputPlaceholder: "Incolla qui la lista degli ingredienti, il nome del prodotto o la descrizione...",
    analyzeTextButton: "Analizza Testo",
    orDivider: "OPPURE",
    loginButton: "Accedi con Google",
    logoutButton: "Esci",
    welcomeUser: "Ciao, ",
  },
  'zh-CN': {
    appTitle: "NutriScan AI",
    scanTab: "扫描",
    historyTab: "历史",
    scanTitle: "扫描新食品",
    scanSubtitle: "上传照片或手动输入详细信息。",
    uploadClick: "点击上传",
    uploadDrag: "或拖放图片",
    analyzing: "分析中...",
    analyzingDesc: "我们的 AI 正在检查成分和营养信息。这可能需要一点时间。",
    historyTitle: "您的饮食日记",
    historyEmpty: "您的历史记录为空。",
    historyEmptyAction: "转到“扫描”标签页分析您的第一项食品！",
    detailSummary: "AI 健康摘要",
    detailIngredients: "成分分析",
    detailPrice: "价格",
    footer: "NutriScan AI. 让健康选择更简单。",
    analysisFailed: "分析失败",
    unknownError: "发生未知错误。",
    textInputLabel: "手动输入详情",
    textInputPlaceholder: "在此粘贴成分表、产品名称或描述...",
    analyzeTextButton: "分析文本",
    orDivider: "或",
    loginButton: "使用 Google 登录",
    logoutButton: "退出登录",
    welcomeUser: "你好，",
  },
  'zh-TW': {
    appTitle: "NutriScan AI",
    scanTab: "掃描",
    historyTab: "歷史",
    scanTitle: "掃描新食品",
    scanSubtitle: "上傳照片或手動輸入詳細資訊。",
    uploadClick: "點擊上傳",
    uploadDrag: "或拖放圖片",
    analyzing: "分析中...",
    analyzingDesc: "我們的 AI 正在檢查成分和營養資訊。這可能需要一點時間。",
    historyTitle: "您的飲食日記",
    historyEmpty: "您的歷史記錄是空的。",
    historyEmptyAction: "前往「掃描」分頁分析您的第一項食品！",
    detailSummary: "AI 健康摘要",
    detailIngredients: "成分分析",
    detailPrice: "價格",
    footer: "NutriScan AI. 讓健康選擇更簡單。",
    analysisFailed: "分析失敗",
    unknownError: "發生未知錯誤。",
    textInputLabel: "手動輸入詳情",
    textInputPlaceholder: "在此貼上成分表、產品名稱或描述...",
    analyzeTextButton: "分析文字",
    orDivider: "或",
    loginButton: "使用 Google 登入",
    logoutButton: "登出",
    welcomeUser: "你好，",
  },
  ja: {
    appTitle: "NutriScan AI",
    scanTab: "スキャン",
    historyTab: "履歴",
    scanTitle: "新しい食品をスキャン",
    scanSubtitle: "写真をアップロードするか、手動で詳細を入力してください。",
    uploadClick: "クリックしてアップロード",
    uploadDrag: "または画像をドラッグ＆ドロップ",
    analyzing: "分析中...",
    analyzingDesc: "AIが原材料と栄養情報を調べています。これには少し時間がかかる場合があります。",
    historyTitle: "食事日記",
    historyEmpty: "履歴は空です。",
    historyEmptyAction: "「スキャン」タブに移動して、最初のアイテムを分析しましょう！",
    detailSummary: "AI健康サマリー",
    detailIngredients: "原材料分析",
    detailPrice: "価格",
    footer: "NutriScan AI. 健康的な選択をより簡単に。",
    analysisFailed: "分析に失敗しました",
    unknownError: "不明なエラーが発生しました。",
    textInputLabel: "詳細を手動入力",
    textInputPlaceholder: "原材料リスト、製品名、または説明をここに貼り付けてください...",
    analyzeTextButton: "テキストを分析",
    orDivider: "または",
    loginButton: "Googleでログイン",
    logoutButton: "ログアウト",
    welcomeUser: "こんにちは、",
  }
};