
import { FoodItem, TranslationDictionary, Language, UserTier } from './types';

export const MOCK_HISTORY: FoodItem[] = [
  {
    id: '1',
    image: 'https://picsum.photos/seed/granola/600/400',
    analysis: {
      productName: "Nature's Valley Granola",
      price: "$5.99",
      summary: "A decent source of fiber, but high in added sugars and contains some processed oils. Best consumed in moderation as part of a balanced diet.",
      ingredients: [
        { name: "Whole Grain Oats", rating: "GOOD", reason: "Excellent source of fiber and nutrients." },
        { name: "Sugar", rating: "POOR", reason: "High in empty calories and can contribute to weight gain." },
        { name: "Canola Oil", rating: "MODERATE", reason: "A processed oil, moderation is key." },
        { name: "Honey", rating: "MODERATE", reason: "A natural sugar, but still a sugar." },
        { name: "Salt", rating: "MODERATE", reason: "Essential for body functions, but excessive intake is harmful." },
        { name: "Soy Lecithin", rating: "NEUTRAL", reason: "An emulsifier, generally considered safe." }
      ]
    },
    location: "SuperMart, Downtown",
    scanDate: new Date(Date.now() - 86400000).toISOString(), // 1 day ago
  },
  {
    id: '2',
    image: 'https://picsum.photos/seed/yogurt/600/400',
    analysis: {
      productName: "Greek Yogurt",
      price: "$3.49",
      summary: "An excellent source of protein and probiotics. This plain version has no added sugar, making it a very healthy choice.",
      ingredients: [
        { name: "Cultured Pasteurized Grade A Nonfat Milk", rating: "GOOD", reason: "Provides protein and beneficial probiotics." },
        { name: "Live and Active Cultures", rating: "GOOD", reason: "Beneficial for gut health." }
      ]
    },
    location: "Health Food Store",
    scanDate: new Date(Date.now() - 2 * 86400000).toISOString(), // 2 days ago
  }
];

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', label: 'Italiano', flag: '🇮🇹' },
  { code: 'zh-CN', label: '简体中文', flag: '🇨🇳' },
  { code: 'zh-TW', label: '繁體中文', flag: '🇹🇼' },
  { code: 'ja', label: '日本語', flag: '🇯🇵' },
];

export const TIER_LIMITS: Record<UserTier, number> = {
  guest: 0,
  free: 5,
  starter: 50,
  pro: 500,
  enterprise: 999999
};

export const TRANSLATIONS: Record<Language, TranslationDictionary> = {
  en: {
    appTitle: "NutriScan AI",
    scanTab: "Scan Food",
    historyTab: "History",
    pricingTab: "Pricing",
    scanTitle: "Scan a New Food",
    scanSubtitle: "Upload a photo of a food product or enter details manually.",
    analysisLanguageLabel: "Analysis Language",
    uploadClick: "Click to upload",
    uploadDrag: "or drag and drop an image",
    analyzing: "Analyzing...",
    analyzingDesc: "Our AI is examining the ingredients and nutritional information. This might take a moment.",
    historyTitle: "Your Food Diary",
    historyEmpty: "Your history is empty.",
    historyEmptyAction: "Go to the 'Scan Food' tab to analyze your first item!",
    detailSummary: "AI Health Summary",
    detailIngredients: "Ingredient Analysis",
    detailPrice: "Price",
    footer: "NutriScan AI. Making healthy choices easier.",
    analysisFailed: "Analysis Failed",
    unknownError: "An unknown error occurred.",
    textInputLabel: "Manually Enter Details",
    textInputPlaceholder: "Paste ingredients list, product name, or description here...",
    analyzeTextButton: "Analyze Text",
    orDivider: "OR",
    loginButton: "Sign in with Google",
    guestLoginButton: "Continue as Guest",
    logoutButton: "Sign out",
    welcomeUser: "Hi, ",
    emailLabel: "Email Address",
    emailPlaceholder: "name@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    signInAction: "Sign In",
    signUpAction: "Sign Up",
    switchToString: "Need an account? Sign up",
    switchToSignIn: "Have an account? Sign in",
    deleteButton: "Delete",
    deleteConfirm: "Are you sure you want to delete this item?",
    cancelButton: "Cancel",
    shareButton: "Share",
    shareModalTitle: "Share Analysis",
    copyLink: "Copy Link",
    copied: "Copied!",
    shareVia: "Share via",
    rescanButton: "Re-scan",
    homeHeroTitle: "Empower Your Eating Choices",
    homeHeroSubtitle: "Instant ingredient analysis and personalized health insights at your fingertips.",
    homeGetStarted: "Get Started",
    feature1Title: "Instant Analysis",
    feature1Desc: "Scan any food product to receive an immediate breakdown of ingredients.",
    feature2Title: "Health Insights",
    feature2Desc: "Simple evaluation of potential health benefits or drawbacks.",
    feature3Title: "Food Journal",
    feature3Desc: "Automatically track your scanned foods and build a personal history.",
    backToHome: "Back to Home",
    guestRestrictionTitle: "Image Scanning Locked",
    guestRestrictionDesc: "Guest users can only use manual text entry. To scan images, please log in.",
    loginToScan: "Login to Scan",
    currentPlan: "Current Plan",
    upgradeAction: "Upgrade",
    planFree: "Free",
    planStarter: "Starter",
    planPro: "Pro",
    planEnterprise: "Enterprise",
    perMonth: "/ month",
    contactUs: "Contact Us",
    features: "Features",
    scansPerMonth: "scans per month",
    publicData: "Data is public",
    prioritySupport: "Priority Support",
    unlimitedScans: "Unlimited Scans",
    customSolutions: "Custom Solutions",
  },
  es: {
    appTitle: "NutriScan AI",
    scanTab: "Escanear",
    historyTab: "Historial",
    pricingTab: "Precios",
    scanTitle: "Escanear Nuevo Alimento",
    scanSubtitle: "Sube una foto de un producto o ingresa detalles manualmente.",
    analysisLanguageLabel: "Idioma del análisis",
    uploadClick: "Clic para subir",
    uploadDrag: "o arrastra y suelta una imagen",
    analyzing: "Analizando...",
    analyzingDesc: "Nuestra IA está examinando los ingredientes y la información nutricional. Esto puede tardar un momento.",
    historyTitle: "Tu Diario de Alimentos",
    historyEmpty: "Tu historial está vacío.",
    historyEmptyAction: "¡Ve a la pestaña 'Escanear' para analizar tu primer artículo!",
    detailSummary: "Resumen de Salud IA",
    detailIngredients: "Análisis de Ingredientes",
    detailPrice: "Precio",
    footer: "NutriScan AI. Facilitando elecciones saludables.",
    analysisFailed: "Análisis Fallido",
    unknownError: "Ocurrió un error desconocido.",
    textInputLabel: "Ingresar Detalles Manualmente",
    textInputPlaceholder: "Pega la lista de ingredientes, nombre del producto o descripción aquí...",
    analyzeTextButton: "Analizar Texto",
    orDivider: "O",
    loginButton: "Iniciar sesión con Google",
    guestLoginButton: "Continuar como invitado",
    logoutButton: "Cerrar sesión",
    welcomeUser: "Hola, ",
    emailLabel: "Dirección de correo",
    emailPlaceholder: "nombre@ejemplo.com",
    passwordLabel: "Contraseña",
    passwordPlaceholder: "••••••••",
    signInAction: "Iniciar sesión",
    signUpAction: "Registrarse",
    switchToString: "¿Necesitas una cuenta? Regístrate",
    switchToSignIn: "¿Tienes una cuenta? Inicia sesión",
    deleteButton: "Eliminar",
    deleteConfirm: "¿Estás seguro de que quieres eliminar este elemento?",
    cancelButton: "Cancelar",
    shareButton: "Compartir",
    shareModalTitle: "Compartir Análisis",
    copyLink: "Copiar enlace",
    copied: "¡Copiado!",
    shareVia: "Compartir vía",
    rescanButton: "Reescanear",
    homeHeroTitle: "Empodera tus elecciones alimentarias",
    homeHeroSubtitle: "Análisis instantáneo de ingredientes y conocimientos de salud personalizados al alcance de tu mano.",
    homeGetStarted: "Comenzar",
    feature1Title: "Análisis Instantáneo",
    feature1Desc: "Escanea cualquier producto alimenticio para recibir un desglose inmediato de los ingredientes.",
    feature2Title: "Conocimientos de Salud",
    feature2Desc: "Evaluación simple de los posibles beneficios o inconvenientes para la salud.",
    feature3Title: "Diario de Alimentos",
    feature3Desc: "Rastrea automáticamente tus alimentos escaneados y crea un historial personal.",
    backToHome: "Volver al Inicio",
    guestRestrictionTitle: "Escaneo de imágenes bloqueado",
    guestRestrictionDesc: "Los invitados solo pueden usar la entrada de texto manual. Para escanear imágenes, inicie sesión.",
    loginToScan: "Iniciar sesión para escanear",
    currentPlan: "Plan actual",
    upgradeAction: "Mejorar",
    planFree: "Gratis",
    planStarter: "Básico",
    planPro: "Pro",
    planEnterprise: "Empresarial",
    perMonth: "/ mes",
    contactUs: "Contáctenos",
    features: "Características",
    scansPerMonth: "escaneos por mes",
    publicData: "Los datos son públicos",
    prioritySupport: "Soporte prioritario",
    unlimitedScans: "Escaneos ilimitados",
    customSolutions: "Soluciones personalizadas",
  },
  fr: {
    appTitle: "NutriScan AI",
    scanTab: "Scanner",
    historyTab: "Historique",
    pricingTab: "Tarifs",
    scanTitle: "Scanner un Aliment",
    scanSubtitle: "Téléchargez une photo ou entrez les détails manuellement.",
    analysisLanguageLabel: "Langue d'analyse",
    uploadClick: "Cliquez pour télécharger",
    uploadDrag: "ou glissez-déposez une image",
    analyzing: "Analyse en cours...",
    analyzingDesc: "Notre IA examine les ingrédients et les informations nutritionnelles. Cela peut prendre un moment.",
    historyTitle: "Votre Journal Alimentaire",
    historyEmpty: "Votre historique est vide.",
    historyEmptyAction: "Allez dans l'onglet 'Scanner' pour analyser votre premier article !",
    detailSummary: "Résumé Santé IA",
    detailIngredients: "Analyse des Ingrédients",
    detailPrice: "Prix",
    footer: "NutriScan AI. Faciliter les choix sains.",
    analysisFailed: "Échec de l'analyse",
    unknownError: "Une erreur inconnue s'est produite.",
    textInputLabel: "Entrer les Détails Manuellement",
    textInputPlaceholder: "Collez la liste des ingrédients, le nom du produit ou la description ici...",
    analyzeTextButton: "Analyser le Texte",
    orDivider: "OU",
    loginButton: "Se connecter avec Google",
    guestLoginButton: "Continuer en invité",
    logoutButton: "Se déconnecter",
    welcomeUser: "Salut, ",
    emailLabel: "Adresse e-mail",
    emailPlaceholder: "nom@exemple.com",
    passwordLabel: "Mot de passe",
    passwordPlaceholder: "••••••••",
    signInAction: "Se connecter",
    signUpAction: "S'inscrire",
    switchToString: "Pas de compte ? Inscrivez-vous",
    switchToSignIn: "Vous avez un compte ? Connectez-vous",
    deleteButton: "Supprimer",
    deleteConfirm: "Êtes-vous sûr de vouloir supprimer cet élément ?",
    cancelButton: "Annuler",
    shareButton: "Partager",
    shareModalTitle: "Partager l'analyse",
    copyLink: "Copier le lien",
    copied: "Copié !",
    shareVia: "Partager via",
    rescanButton: "Rescanner",
    homeHeroTitle: "Maîtrisez vos choix alimentaires",
    homeHeroSubtitle: "Analyse instantanée des ingrédients et informations santé personnalisées à portée de main.",
    homeGetStarted: "Commencer",
    feature1Title: "Analyse Instantanée",
    feature1Desc: "Scannez n'importe quel produit alimentaire pour obtenir une analyse immédiate des ingrédients.",
    feature2Title: "Informations Santé",
    feature2Desc: "Évaluation simple des avantages ou inconvénients potentiels pour la santé.",
    feature3Title: "Journal Alimentaire",
    feature3Desc: "Suivez automatiquement vos aliments scannés et construisez un historique personnel.",
    backToHome: "Retour à l'accueil",
    guestRestrictionTitle: "Scan d'image verrouillé",
    guestRestrictionDesc: "Les invités ne peuvent utiliser que la saisie manuelle. Pour scanner des images, connectez-vous.",
    loginToScan: "Connexion pour scanner",
    currentPlan: "Plan actuel",
    upgradeAction: "Mettre à niveau",
    planFree: "Gratuit",
    planStarter: "Débutant",
    planPro: "Pro",
    planEnterprise: "Entreprise",
    perMonth: "/ mois",
    contactUs: "Contactez-nous",
    features: "Fonctionnalités",
    scansPerMonth: "scans par mois",
    publicData: "Les données sont publiques",
    prioritySupport: "Support prioritaire",
    unlimitedScans: "Scans illimités",
    customSolutions: "Solutions personnalisées",
  },
  de: {
    appTitle: "NutriScan AI",
    scanTab: "Scannen",
    historyTab: "Verlauf",
    pricingTab: "Preise",
    scanTitle: "Neues Lebensmittel scannen",
    scanSubtitle: "Foto hochladen oder Details manuell eingeben.",
    analysisLanguageLabel: "Analysesprache",
    uploadClick: "Zum Hochladen klicken",
    uploadDrag: "oder Bild hierher ziehen",
    analyzing: "Analysieren...",
    analyzingDesc: "Unsere KI prüft die Zutaten und Nährwertinformationen. Dies kann einen Moment dauern.",
    historyTitle: "Ihr Ernährungstagebuch",
    historyEmpty: "Ihr Verlauf ist leer.",
    historyEmptyAction: "Gehen Sie zum Tab 'Scannen', um Ihren ersten Artikel zu analysieren!",
    detailSummary: "KI-Gesundheitszusammenfassung",
    detailIngredients: "Zutatenanalyse",
    detailPrice: "Preis",
    footer: "NutriScan AI. Gesunde Entscheidungen leichter gemacht.",
    analysisFailed: "Analyse fehlgeschlagen",
    unknownError: "Ein unbekannter Fehler ist aufgetreten.",
    textInputLabel: "Details Manuell Eingeben",
    textInputPlaceholder: "Fügen Sie hier die Zutatenliste, den Produktnamen oder die Beschreibung ein...",
    analyzeTextButton: "Text Analysieren",
    orDivider: "ODER",
    loginButton: "Mit Google anmelden",
    guestLoginButton: "Als Gast fortfahren",
    logoutButton: "Abmelden",
    welcomeUser: "Hallo, ",
    emailLabel: "E-Mail-Adresse",
    emailPlaceholder: "name@beispiel.com",
    passwordLabel: "Passwort",
    passwordPlaceholder: "••••••••",
    signInAction: "Anmelden",
    signUpAction: "Registrieren",
    switchToString: "Kein Konto? Registrieren",
    switchToSignIn: "Haben Sie ein Konto? Anmelden",
    deleteButton: "Löschen",
    deleteConfirm: "Sind Sie sicher, dass Sie dieses Element löschen möchten?",
    cancelButton: "Abbrechen",
    shareButton: "Teilen",
    shareModalTitle: "Analyse teilen",
    copyLink: "Link kopieren",
    copied: "Kopiert!",
    shareVia: "Teilen über",
    rescanButton: "Neu scannen",
    homeHeroTitle: "Treffen Sie bewusste Essentscheidungen",
    homeHeroSubtitle: "Sofortige Zutatenanalyse und personalisierte Gesundheitsinformationen auf Knopfdruck.",
    homeGetStarted: "Loslegen",
    feature1Title: "Sofortige Analyse",
    feature1Desc: "Scannen Sie jedes Lebensmittelprodukt für eine sofortige Aufschlüsselung der Zutaten.",
    feature2Title: "Gesundheitseinblicke",
    feature2Desc: "Einfache Bewertung potenzieller gesundheitlicher Vor- oder Nachteile.",
    feature3Title: "Ernährungstagebuch",
    feature3Desc: "Verfolgen Sie automatisch Ihre gescannten Lebensmittel und erstellen Sie einen persönlichen Verlauf.",
    backToHome: "Zurück zur Startseite",
    guestRestrictionTitle: "Bildscan gesperrt",
    guestRestrictionDesc: "Gäste können nur die manuelle Texteingabe nutzen. Zum Scannen von Bildern bitte anmelden.",
    loginToScan: "Zum Scannen anmelden",
    currentPlan: "Aktueller Plan",
    upgradeAction: "Upgrade",
    planFree: "Kostenlos",
    planStarter: "Starter",
    planPro: "Pro",
    planEnterprise: "Enterprise",
    perMonth: "/ Monat",
    contactUs: "Kontaktieren Sie uns",
    features: "Funktionen",
    scansPerMonth: "Scans pro Monat",
    publicData: "Daten sind öffentlich",
    prioritySupport: "Bevorzugter Support",
    unlimitedScans: "Unbegrenzte Scans",
    customSolutions: "Maßgeschneiderte Lösungen",
  },
  it: {
    appTitle: "NutriScan AI",
    scanTab: "Scansione",
    historyTab: "Cronologia",
    pricingTab: "Prezzi",
    scanTitle: "Scansiona Nuovo Cibo",
    scanSubtitle: "Carica una foto o inserisci i dettagli manualmente.",
    analysisLanguageLabel: "Lingua analisi",
    uploadClick: "Clicca per caricare",
    uploadDrag: "o trascina e rilascia un'immagine",
    analyzing: "Analisi in corso...",
    analyzingDesc: "La nostra IA sta esaminando gli ingredienti e le informazioni nutrizionali. Potrebbe richiedere un momento.",
    historyTitle: "Il Tuo Diario Alimentare",
    historyEmpty: "La tua cronologia è vuota.",
    historyEmptyAction: "Vai alla scheda 'Scansione' per analizzare il tuo primo articolo!",
    detailSummary: "Riepilogo Salute IA",
    detailIngredients: "Analisi degli Ingredienti",
    detailPrice: "Prezzo",
    footer: "NutriScan AI. Scelte sane rese più facili.",
    analysisFailed: "Analisi Fallita",
    unknownError: "Si è verificato un errore sconosciuto.",
    textInputLabel: "Inserisci Manualmente i Dettagli",
    textInputPlaceholder: "Incolla qui la lista degli ingredienti, il nome del prodotto o la descrizione...",
    analyzeTextButton: "Analizza Testo",
    orDivider: "OPPURE",
    loginButton: "Accedi con Google",
    guestLoginButton: "Continua come ospite",
    logoutButton: "Esci",
    welcomeUser: "Ciao, ",
    emailLabel: "Indirizzo Email",
    emailPlaceholder: "nome@esempio.com",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    signInAction: "Accedi",
    signUpAction: "Registrati",
    switchToString: "Non hai un account? Registrati",
    switchToSignIn: "Hai già un account? Accedi",
    deleteButton: "Elimina",
    deleteConfirm: "Sei sicuro di voler eliminare questo elemento?",
    cancelButton: "Annulla",
    shareButton: "Condividi",
    shareModalTitle: "Condividi Analisi",
    copyLink: "Copia Link",
    copied: "Copiato!",
    shareVia: "Condividi tramite",
    rescanButton: "Riscansiona",
    homeHeroTitle: "Potenzia le tue scelte alimentari",
    homeHeroSubtitle: "Analisi istantanea degli ingredienti e approfondimenti sulla salute personalizzati a portata di mano.",
    homeGetStarted: "Inizia",
    feature1Title: "Analisi Istantanea",
    feature1Desc: "Scansiona qualsiasi prodotto alimentare per ricevere un'analisi immediata degli ingredienti.",
    feature2Title: "Approfondimenti Salute",
    feature2Desc: "Valutazione semplice dei potenziali benefici o svantaggi per la salute.",
    feature3Title: "Diario Alimentare",
    feature3Desc: "Traccia automaticamente gli alimenti scansionati e costruisci una cronologia personale.",
    backToHome: "Torna alla Home",
    guestRestrictionTitle: "Scansione immagini bloccata",
    guestRestrictionDesc: "Gli ospiti possono utilizzare solo l'inserimento manuale del testo. Per scansionare immagini, accedi.",
    loginToScan: "Accedi per scansionare",
    currentPlan: "Piano attuale",
    upgradeAction: "Aggiorna",
    planFree: "Gratuito",
    planStarter: "Starter",
    planPro: "Pro",
    planEnterprise: "Enterprise",
    perMonth: "/ mese",
    contactUs: "Contattaci",
    features: "Caratteristiche",
    scansPerMonth: "scansioni al mese",
    publicData: "I dati sono pubblici",
    prioritySupport: "Supporto prioritario",
    unlimitedScans: "Scansioni illimitate",
    customSolutions: "Soluzioni personalizzate",
  },
  'zh-CN': {
    appTitle: "NutriScan AI",
    scanTab: "扫描",
    historyTab: "历史",
    pricingTab: "价格",
    scanTitle: "扫描新食品",
    scanSubtitle: "上传照片或手动输入详细信息。",
    analysisLanguageLabel: "分析语言",
    uploadClick: "点击上传",
    uploadDrag: "或拖放图片",
    analyzing: "分析中...",
    analyzingDesc: "我们的 AI 正在检查成分和营养信息。这可能需要一点时间。",
    historyTitle: "您的饮食日记",
    historyEmpty: "您的历史记录为空。",
    historyEmptyAction: "转到“扫描”标签页分析您的第一项食品！",
    detailSummary: "AI 健康摘要",
    detailIngredients: "成分分析",
    detailPrice: "价格",
    footer: "NutriScan AI. 让健康选择更简单。",
    analysisFailed: "分析失败",
    unknownError: "发生未知错误。",
    textInputLabel: "手动输入详情",
    textInputPlaceholder: "在此粘贴成分表、产品名称或描述...",
    analyzeTextButton: "分析文本",
    orDivider: "或",
    loginButton: "使用 Google 登录",
    guestLoginButton: "以访客身份继续",
    logoutButton: "退出登录",
    welcomeUser: "你好，",
    emailLabel: "电子邮件",
    emailPlaceholder: "name@example.com",
    passwordLabel: "密码",
    passwordPlaceholder: "••••••••",
    signInAction: "登录",
    signUpAction: "注册",
    switchToString: "没有账号？注册",
    switchToSignIn: "已有账号？登录",
    deleteButton: "删除",
    deleteConfirm: "您确定要删除此项目吗？",
    cancelButton: "取消",
    shareButton: "分享",
    shareModalTitle: "分享分析",
    copyLink: "复制链接",
    copied: "已复制！",
    shareVia: "分享至",
    rescanButton: "重新扫描",
    homeHeroTitle: "掌握您的饮食选择",
    homeHeroSubtitle: "触手可及的即时成分分析和个性化健康见解。",
    homeGetStarted: "开始使用",
    feature1Title: "即时分析",
    feature1Desc: "扫描任何食品即可立即获得成分明细。",
    feature2Title: "健康见解",
    feature2Desc: "对潜在健康益处或缺点的简单评估。",
    feature3Title: "饮食日记",
    feature3Desc: "自动跟踪您扫描的食品并建立个人历史记录。",
    backToHome: "返回首页",
    guestRestrictionTitle: "图片扫描已锁定",
    guestRestrictionDesc: "访客只能使用手动文本输入。如需扫描图片，请登录。",
    loginToScan: "登录以扫描",
    currentPlan: "当前计划",
    upgradeAction: "升级",
    planFree: "免费",
    planStarter: "入门版",
    planPro: "专业版",
    planEnterprise: "企业版",
    perMonth: "/ 月",
    contactUs: "联系我们",
    features: "功能",
    scansPerMonth: "次扫描/月",
    publicData: "数据公开",
    prioritySupport: "优先支持",
    unlimitedScans: "无限扫描",
    customSolutions: "定制解决方案",
  },
  'zh-TW': {
    appTitle: "NutriScan AI",
    scanTab: "掃描",
    historyTab: "歷史",
    pricingTab: "價格",
    scanTitle: "掃描新食品",
    scanSubtitle: "上傳照片或手動輸入詳細資訊。",
    analysisLanguageLabel: "分析語言",
    uploadClick: "點擊上傳",
    uploadDrag: "或拖放圖片",
    analyzing: "分析中...",
    analyzingDesc: "我們的 AI 正在檢查成分和營養資訊。這可能需要一點時間。",
    historyTitle: "您的飲食日記",
    historyEmpty: "您的歷史記錄是空的。",
    historyEmptyAction: "前往「掃描」分頁分析您的第一項食品！",
    detailSummary: "AI 健康摘要",
    detailIngredients: "成分分析",
    detailPrice: "價格",
    footer: "NutriScan AI. 讓健康選擇更簡單。",
    analysisFailed: "分析失敗",
    unknownError: "發生未知錯誤。",
    textInputLabel: "手動輸入詳情",
    textInputPlaceholder: "在此貼上成分表、產品名稱或描述...",
    analyzeTextButton: "分析文本",
    orDivider: "或",
    loginButton: "使用 Google 登入",
    guestLoginButton: "以訪客身份繼續",
    logoutButton: "登出",
    welcomeUser: "你好，",
    emailLabel: "電子郵件",
    emailPlaceholder: "name@example.com",
    passwordLabel: "密碼",
    passwordPlaceholder: "••••••••",
    signInAction: "登入",
    signUpAction: "註冊",
    switchToString: "沒有帳號？註冊",
    switchToSignIn: "已有帳號？登入",
    deleteButton: "刪除",
    deleteConfirm: "您確定要刪除此項目嗎？",
    cancelButton: "取消",
    shareButton: "分享",
    shareModalTitle: "分享分析",
    copyLink: "複製連結",
    copied: "已複製！",
    shareVia: "分享至",
    rescanButton: "重新掃描",
    homeHeroTitle: "掌握您的飲食選擇",
    homeHeroSubtitle: "觸手可及的即時成分分析和個人化健康見解。",
    homeGetStarted: "開始使用",
    feature1Title: "即時分析",
    feature1Desc: "掃描任何食品即可立即獲得成分明細。",
    feature2Title: "健康見解",
    feature2Desc: "對潛在健康益處或缺點的簡單評估。",
    feature3Title: "飲食日記",
    feature3Desc: "自動追蹤您掃描的食品並建立個人歷史記錄。",
    backToHome: "返回首頁",
    guestRestrictionTitle: "圖片掃描已鎖定",
    guestRestrictionDesc: "訪客只能使用手動文字輸入。如需掃描圖片，請登入。",
    loginToScan: "登入以掃描",
    currentPlan: "目前方案",
    upgradeAction: "升級",
    planFree: "免費",
    planStarter: "入門版",
    planPro: "專業版",
    planEnterprise: "企業版",
    perMonth: "/ 月",
    contactUs: "聯繫我們",
    features: "功能",
    scansPerMonth: "次掃描/月",
    publicData: "數據公開",
    prioritySupport: "優先支援",
    unlimitedScans: "無限掃描",
    customSolutions: "客製化解決方案",
  },
  ja: {
    appTitle: "NutriScan AI",
    scanTab: "スキャン",
    historyTab: "履歴",
    pricingTab: "料金",
    scanTitle: "新しい食品をスキャン",
    scanSubtitle: "食品の写真をアップロードするか、詳細を手動で入力してください。",
    analysisLanguageLabel: "分析言語",
    uploadClick: "クリックしてアップロード",
    uploadDrag: "または画像をドラッグ＆ドロップ",
    analyzing: "分析中...",
    analyzingDesc: "AIが成分と栄養情報を検査しています。少々お待ちください。",
    historyTitle: "食事日記",
    historyEmpty: "履歴は空です。",
    historyEmptyAction: "「スキャン」タブに移動して、最初の食品を分析しましょう！",
    detailSummary: "AI健康サマリー",
    detailIngredients: "成分分析",
    detailPrice: "価格",
    footer: "NutriScan AI. 健康的な選択をより簡単に。",
    analysisFailed: "分析に失敗しました",
    unknownError: "不明なエラーが発生しました。",
    textInputLabel: "詳細を手動入力",
    textInputPlaceholder: "成分表、製品名、または説明をここに貼り付けてください...",
    analyzeTextButton: "テキストを分析",
    orDivider: "または",
    loginButton: "Googleでログイン",
    guestLoginButton: "ゲストとして続行",
    logoutButton: "ログアウト",
    welcomeUser: "こんにちは、",
    emailLabel: "メールアドレス",
    emailPlaceholder: "name@example.com",
    passwordLabel: "パスワード",
    passwordPlaceholder: "••••••••",
    signInAction: "ログイン",
    signUpAction: "登録",
    switchToString: "アカウントをお持ちでないですか？登録",
    switchToSignIn: "アカウントをお持ちですか？ログイン",
    deleteButton: "削除",
    deleteConfirm: "この項目を削除してもよろしいですか？",
    cancelButton: "キャンセル",
    shareButton: "共有",
    shareModalTitle: "分析を共有",
    copyLink: "リンクをコピー",
    copied: "コピーしました！",
    shareVia: "共有方法",
    rescanButton: "再スキャン",
    homeHeroTitle: "食の選択をよりスマートに",
    homeHeroSubtitle: "瞬時の成分分析とパーソナライズされた健康アドバイスをあなたの手元に。",
    homeGetStarted: "始める",
    feature1Title: "瞬時分析",
    feature1Desc: "食品をスキャンするだけで、成分の詳細をすぐに確認できます。",
    feature2Title: "健康アドバイス",
    feature2Desc: "健康へのメリットや注意点をわかりやすく評価します。",
    feature3Title: "食事日記",
    feature3Desc: "スキャンした食品を自動的に記録し、個人の履歴を作成します。",
    backToHome: "ホームに戻る",
    guestRestrictionTitle: "画像スキャンはロックされています",
    guestRestrictionDesc: "ゲストは手動テキスト入力のみ利用可能です。画像をスキャンするにはログインしてください。",
    loginToScan: "ログインしてスキャン",
    currentPlan: "現在のプラン",
    upgradeAction: "アップグレード",
    planFree: "無料",
    planStarter: "スターター",
    planPro: "プロ",
    planEnterprise: "エンタープライズ",
    perMonth: "/ 月",
    contactUs: "お問い合わせ",
    features: "機能",
    scansPerMonth: "スキャン/月",
    publicData: "データは公開されます",
    prioritySupport: "優先サポート",
    unlimitedScans: "無制限スキャン",
    customSolutions: "カスタムソリューション",
  }
};
